[package]
name = "oxidized-landlord"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
base64 = "0.22.1"
rocket = {version = "0.5.1", features = ["json"]}
serde_json = "1.0.133"
tokio = { version = "1.42.0", features = ["net", "process"] }
webrtc = "0.12.0"
